### ISSUE TITLE
Custom server?

### ISSUE THREAD

**Issue by LinuxGamer** [brandly/irc#50] opened 2018-08-18 20:37 UTC
It's possible to join a custom server? by adding then or editing the a file?
because i want to use it to chat on osu!irc

**Comment by brandly** [comment] 2018-08-19 03:03
I think this is a duplicate of #45. I should probably change the drop down to a normal input field for now, and then we can see if there’s a better way to kinda support both.

**Closed** 2018-09-18 02:10 UTC

**Comment by brandly** [comment] 2018-09-18 03:36
check out [v0.4.0](https://github.com/brandly/irc/releases/tag/0.4.0)!!
